version: "3.9"

services:
  app:
    image: php:8.2-apache
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_USER=appuser
      - DB_PASSWORD=apppass
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 3s
      retries: 5
    # Install mysqli extension at container start (simple demo approach)
    command: bash -lc "docker-php-ext-install mysqli && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

# Usage:
#   docker compose up -d
#   Open http://localhost:8080
